### ISSUE TITLE
请问为何编辑器的图标无法正常显示

### ISSUE THREAD

**Issue by howie95** [hinesboy/mavonEditor#109]
学习webpack和vue没多久，最近在自己写博客的前端，按照readme里的方法1将编辑器插入组件后，编辑器正常显示了，样式也在，可是图标一个都没有显示，一开始我怀疑是自己项目的问题，可是我用vue-cli初始化了一个普通webpack项目和一个webpack-simple项目，两次尝试插入编辑器都不能显示图标，查看html代码猜测编辑器使用了font-awesome的图标，可是搜索文档并没有看到有对fa进行定义，想问一下为什么会出现这种情况，感谢！

版本
node v8.5.0
vue-cli 2.9.1
mavon-editor 2.2.10

**Comment by CHENXCHEN** [comment]
将项目clone下来,然后`npm run dev`,在本地尝试看看能不能正常显示?
如果可以正常显示的话应该是代码问题,dev代码位于`mavonEditor/src/dev`目录下

**Comment by howie95** [comment]
非常感谢，clone下来之后在本地是可以显示图标的，可是我在vue-cli初始化一个新的webpack项目里插入的编辑器还是不能显示图标。。似乎在mavon-editor.vue里import的css文件都没有生效，我把font文件夹拷贝到项目目录里，在引用编辑器的组件里import字体的css之后图标就显示了。

**Comment by CHENXCHEN** [comment]
不需要手动拷贝出来..没有在代码中引入css文件吧?
参考[gh-pages分支](https://github.com/hinesboy/mavonEditor/tree/gh-pages)

**Comment by howie95** [comment]
我明白了。。当时发现问题还查看了好几遍readme里面如何引入那里看是不是自己漏了什么东西，结果就是漏了要手动引入css文件那一行，以为只要引入编辑器就好了。。非常感谢！

**Comment by wtto00** [comment]
在vue的style标签中，引入样式文件
```css
@import '~mavon-editor/dist/css/index.css';
```
工具栏图标无法显示，再加上下边的字体引入就可以先显示了：
```css
@font-face {
  font-family: fontello;
  src: url(/fonts/fontello.e73a0647.eot);
  src: url(/fonts/fontello.e73a0647.eot#iefix) format('embedded-opentype'),
    url(/fonts/fontello.8d4a4e6f.woff2) format('woff2'),
    url(/fonts/fontello.a782baa8.woff) format('woff'),
    url(/fonts/fontello.068ca2b3.ttf) format('truetype'), url([objectObject]) format('svg');
  font-weight: 400;
  font-style: normal;
}
```

> 使用的@vue/cli创建的项目
