### ISSUE TITLE
How to disable github-css-stylesheet?

### ISSUE THREAD

**Issue by GrayedFox** [hinesboy/mavonEditor#340]
Hi there, thanks for creating such an awesome in-line markdown editor!

I am currently trying to change the rendered markdown by styling elements under `.markdown-body`, however I find that the github-css-stylesheet often takes preference.

For example, I'd like to change the colour of links, like so:

```css
.markdown-body a {
    color: #2ab6f6;
    text-decoration: none;
}
```
However this is overwritten by the GH style sheet, as seen in the below screenshot:

![screenshot from 2018-10-20 17-15-32](https://user-images.githubusercontent.com/6493307/47257254-d55d3c00-d48b-11e8-8ab9-6bf9bfa2ce97.png)
