### ISSUE TITLE
如何去除代码高亮的pre padding

### ISSUE THREAD

**Issue by cat998** [hinesboy/mavonEditor#429]
![image](https://user-images.githubusercontent.com/30257294/58222591-234f6080-7d49-11e9-82e3-3fe736a94da6.png)

代码高亮时有一部分padding，能否去掉？我修改了mavon-editor里面的pre但是没有效果。。

**Comment by hlr7999** [comment]
```css
.markdown-body .highlight pre, 
.markdown-body pre {
  padding: 3px !important;
}
```
这样应该可以
