### ISSUE TITLE
能否支持一些样式的自定义？

### ISSUE THREAD

**Issue by Arvin-He** [hinesboy/mavonEditor#437]
这个markdown编辑器真心强大，将这个编辑器用作阅读器使用也很好，如果能开放几个选项支持一些样式就更完美了。比如：

1. 编辑器的边框能否隐藏？
2. 字体的颜色能否支持自定义？
3. 编辑器的背景色能否支持自定义？

![image](https://user-images.githubusercontent.com/16191792/59002500-4566d980-8845-11e9-9c40-88aa4028f566.png)

**Comment by chen-i** [comment]
可以用/deep/覆盖
![1](https://user-images.githubusercontent.com/37339618/59576369-1af10800-90f2-11e9-98bb-1bcbd8566ad9.PNG)
![2](https://user-images.githubusercontent.com/37339618/59576375-1debf880-90f2-11e9-9f0b-ecf7b7c73f84.PNG)

**Comment by Arvin-He** [comment]
非常感谢, 已解决!

**Comment by j770657446** [comment]
为什么我这边还是不行  可以介绍的详细点么

**Comment by chen-i** [comment]
不知道你怎么写的，有可能是/deep/没作用到对应的元素上面，或者你的vue loader版本不支持/deep/, 可以看下
https://vue-loader.vuejs.org/zh/guide/scoped-css.html#%E6%B7%B7%E7%94%A8%E6%9C%AC%E5%9C%B0%E5%92%8C%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F

j770657446 <notifications@github.com> 于2019年7月3日周三 下午5:21写道：

**Comment by Arvin-He** [comment]
@j770657446 
我是这么做的, 可以参考下:

```html
<template>
   // 这是你的markdown编辑器tag
   <div class="editor-div">
      <mavon-editor v-model="article.content" defaultOpen="preview" :boxShadow="false" :subfield="false" :editable="false" :toolbarsFlag="false"/>
  </div>
</template>

```

然后是css, 注意: **必须要有全局样式标签`<style></style>`**,否则深度作用无效,也就是有2个<style>标签.

```css
<style>
/* 这个全局样式标签不上少，否则深度作用选择器就失效了 */
</style>

<style scoped>
.editor-div >>> .v-note-wrapper {
    z-index: 0;
  }
  .editor-div >>> .v-note-wrapper .v-note-panel {
    border: 1px solid #ffffff;
  }
  .editor-div >>> .v-note-wrapper .v-note-panel .v-note-show .v-show-content {
    border: 1px solid #ffffff;
    padding-left: 0;
  }
</style>
```
