### ISSUE TITLE
工具栏部分样式异常

### ISSUE THREAD

**Issue by whoami1231** [hinesboy/mavonEditor#464]
![image](https://user-images.githubusercontent.com/40268529/61867737-717c0e00-af0a-11e9-81e2-29df2141fa1e.png)

**Comment by whoami1231** [comment]
请问有什么解决方案么？

样式文件已经导入

**Comment by hhui64** [comment]
__问题原因：__
一般是引入了 normalize.css 引起的
normalize.css 中有这一段样式，该样式是让 type="button" 的 div 看起来像 button
```css
button, [type="button"], [type="reset"], [type="submit"] {
    -webkit-appearance: button;
}
```

__解决方案：__
将 -webkit-appearance 属性覆盖掉即可
```css
div.op-icon.fa.dropdown.dropdown-wrapper {
    -webkit-appearance: unset !important;
}
```
> !important 可以不添加，视情况决定
