### ISSUE TITLE
前端解析 markdown 样式问题

### ISSUE THREAD

**Issue by pyzworld** [hinesboy/mavonEditor#69]
我用 markdown-it 解析渲染到前端 和在编辑器里面的样式相差很大。没有样式 很多语法都不支持 请问在页面中显示 如何与在编辑器 预览的一样。

**Comment by CHENXCHEN** [comment]
@pyzworld 这个需要将markdown的css样式也引入到网页中，目前你可以在`mavonEditor`的代码里找到引用的markdown的css样式，目前还没有对样式做分离，下一个版本对md样式做分离

**Comment by zgj233** [comment]
@CHENXCHEN  请问下，如果是修改一些简单的css 样式，比如
```css 
.v-note-wrapper .v-note-panel {
  box-shadow:none;
}
``` 
必须修改源码里面的css 吗？ 为何我在页面上试图修改样式总是不成功？
